WeVolunteer/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using WeVolunteer.Core.Constants;
using WeVolunteer.Core.Models.User;
using WeVolunteer.Core.Services.User;
using WeVolunteer.Extensions;

namespace WeVolunteer.Areas.Admin.Controllers
{
    
    public class UserController : AdminController
    {
        private readonly IUserService users;
        private readonly IMemoryCache cache;
        private readonly ILogger logger;
        public UserController(IUserService _users,
                              IMemoryCache _cache,
                              ILogger<UserController> _logger)
        {
            this.users = _users;
            this.cache = _cache;
            this.logger = _logger;
        }

        [Route("/Admin/User/All")]
        public IActionResult All()
        {
            var users = this.cache.Get<IEnumerable<UserServiceModel>>("UsersCacheKey");
            if(users == null)
            {
                users = this.users.All();

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromSeconds(10));

                this.cache.Set("UsersCacheKey", users, cacheOptions);
            }
            return View(users);
        }

        //Forget the data of the user but the id remains

        [HttpPost]
        public async Task<IActionResult> Forget(string Id)
        {
            try
            {
                await this.users.Forget(Id);
                TempData[MessageConstant.SuccessMessage] = "Successfully deleted user";
            }
            catch (Exception)
            {
                TempData[MessageConstant.ErrorMessage] = "Unsuccessfully deleted user";
                this.logger.LogInformation("User {0} could not be deleted!", Id);
            }
            return RedirectToAction(nameof(All));
        }
    }
}

WeVolunteer/Controllers/OrganizationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WeVolunteer.Extensions;
using WeVolunteer.Core.Services.Organization;
using WeVolunteer.Core.Models.Organization;
using WeVolunteer.Core.Constants;
using WeVolunteer.Core.Services.Category;
using WeVolunteer.Core.Services.User;

namespace WeVolunteer.Controllers
{
    [AutoValidateAntiforgeryToken]
    [Authorize]
    public class OrganizationController : Controller
    {
        private readonly IOrganizationService organizationService;
        private readonly ICategoryService categoryService;
        private readonly IUserService userService;
        private readonly ILogger logger;

        public OrganizationController(IOrganizationService _organizationService, 
                                      ICategoryService _categoryService,
                                      IUserService _userService,
                                      ILogger<OrganizationController> _logger)
        {
            this.organizationService = _organizationService;
            this.categoryService = _categoryService;
            this.userService = _userService;
            this.logger = _logger;
        }

        [HttpGet]
        public IActionResult Become()
        {
            if (this.organizationService.ExistsById(this.User.Id()))
            {
                TempData[MessageConstant.WarningMessage] = "You are already an organization!";
                this.logger.LogInformation("User {0} tried to become organization again!", this.User.Id());
                return RedirectToAction(nameof(CauseController.All), "Cause");
            }

            BecomeOrganizationFormModel model = new BecomeOrganizationFormModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Become(BecomeOrganizationFormModel model)
        {
            var userId = this.User.Id();

            if (this.organizationService.ExistsById(userId))
            {
                TempData[MessageConstant.WarningMessage] = "You are already an organization!";
                this.logger.LogInformation("User {0} tried to become organization again!", this.User.Id());
                return RedirectToAction(nameof(CauseController.All), "Cause");
            }

            if (this.organizationService.NameExists(model.Name))
            {
                TempData[MessageConstant.ErrorMessage] = "Organization with such name already exists. Enter another one.";
                return View(model);
            }

            if (!ModelState.IsValid)
            {
                TempData[MessageConstant.ErrorMessage] = "Invalid registration of organization";
                return View(model);
            }

            try
            {
                await this.organizationService.CreateAsync(userId,
                                            model.Name,
                                            model.Headquarter,
                                            model.Description,
                                            model.Image);
            }
            catch (Exception)
            {
                this.logger.LogInformation("{0} did not manage to become organization!", userId);
                TempData[MessageConstant.ErrorMessage] = "Unsuccessfully becoming an organization";
            }
            
            TempData[MessageConstant.SuccessMessage] = "You have become an organization.";

            return RedirectToAction(nameof(CauseController.All), "Cause");
        }

        [AllowAnonymous]
        public IActionResult All([FromQuery] AllOrganizationsQueryModel query)
        {
            var queryResult = this.organizationService.All(
                query.Category,
                query.SearchTerm,
                query.CurrentPage,
                AllOrganizationsQueryModel.OrganizationsPerPage);

            query.TotalOrganizationsCount = queryResult.TotalOrganizationsCount;
            query.Organizations = queryResult.Organizations;

            var organizationCategories = this.categoryService.AllCategoriesNames();
            query.Categories = organizationCategories;

            return View(query);
        }
    }
}

WeVolunteer/Controllers/WeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WeVolunteer.Controllers
{
    [AllowAnonymous]
    public class WeController : Controller
    {
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Help()
        {
            return View();
        }
    }
}

WeVolunteer/Views/Shared/_FooterPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using WeVolunteer.Infrastructure.Data.Entities.Account
@using WeVolunteer.Infrastructure.Data.Entities
@inject SignInManager<User> SignInManager;
@inject UserManager<User> UserManager;
@if (!SignInManager.IsSignedIn(User)){
   <li class="footer-menu-item"><a asp-controller="User" asp-action="Login" class="footer-menu-link">Become a volunteer</a></li>
}

WeVolunteer/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>WeVolunteer</title>

        <!-- CSS FILES -->        
        <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <link href="~/lib/toastr/toastr.min.css" rel="stylesheet">

        <link href="~/bootstrap/css/bootstrap-icons.css" rel="stylesheet">

        <link href="~/bootstrap/css/templatemo-kind-heart-charity.css" rel="stylesheet">

        <!-- Script to Load the main JS page-->
        <script src="~/bootstrap/js/jquery.min.js"></script>

    </head>
    
    <body id="section_1">
       <partial name="_UserMessages" />
        <header class="site-header">
            <div class="container">
                <div class="row">
                    
                    <div class="col-lg-8 col-12 d-flex flex-wrap">
                        <p class="d-flex me-4 mb-0">
                            <i class="bi-geo-alt me-2"></i>
                            Ruse, Bulgaria
                        </p>

                        <p class="d-flex mb-0">
                            <i class="bi-envelope me-2"></i>

                            <a href="mailto:mariakirilova2004@gmail.com">
                                mariakirilova2004@gmail.com
                            </a>
                        </p>
                    </div>

                    <div class="col-lg-3 col-12 ms-auto d-lg-block d-none">
                        <ul class="social-icon">
                            @*<li class="social-icon-item">
                                <a href="#" class="social-icon-link bi-twitter"></a>
                            </li>*@

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link bi-facebook"></a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link bi-instagram"></a>
                            </li>

                            @*<li class="social-icon-item">
                                <a href="#" class="social-icon-link bi-youtube"></a>
                            </li>

                            <li class="social-icon-item">
                                <a href="#" class="social-icon-link bi-whatsapp"></a>
                            </li>*@
                        </ul>
                    </div>

                </div>
            </div>
        </header>

        <nav class="navbar navbar-expand-lg bg-light shadow-lg">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/bootstrap/images/logo.png" class="logo img-fluid" alt="WeVolunteer">
                    <span>
                        WeVolunteer
                        <small>Non-profit Organization</small>
                    </span>
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item">
                            <a class="nav-link click-scroll"></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link click-scroll"  asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link click-scroll"  asp-controller="Cause" asp-action="All">Causes</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link click-scroll"  asp-controller="Organization" asp-action="All">Organizations</a>
                        </li>

                        <li class="nav-item ms-3">
                            <a class="nav-link custom-btn custom-border-btn btn" asp-area="" asp-controller="We" asp-action="Help">Help us</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>


        <main> @RenderBody() </main>

        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-12 mb-4">
                        <img src="~/bootstrap/images/logo.png" class="logo img-fluid" alt="">
                    </div>

                    <div class="col-lg-4 col-md-6 col-12 mb-4">
                        <h5 class="site-footer-title mb-3">Quick Links</h5>

                        <ul class="footer-menu">

@*                            <li class="footer-menu-item"><a asp-controller="We" asp-action="Story" class="footer-menu-link">Our Story</a></li>
*@
                            <li class="footer-menu-item"><a asp-controller="Organization" asp-action="All" class="footer-menu-link">Organizations</a></li>

                            <li class="footer-menu-item"><a asp-controller="Cause" asp-action="All" class="footer-menu-link">Causes</a></li>
                            
                            <partial name="_FooterPartial" />
                            
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 col-12 mx-auto">
                        <h5 class="site-footer-title mb-3">Contact Infomation</h5>

                        <p class="text-white d-flex mb-2">
                            <i class="bi-telephone me-2"></i>

                            <a href="tel: 088-888-8888" class="site-footer-link">
                                088-888-8888
                            </a>
                        </p>

                        <p class="text-white d-flex">
                            <i class="bi-envelope me-2"></i>

                            <a href="mailto:mariakirilova2004@gmail.com" class="site-footer-link">
                                mariakirilova2004@gmail.com
                            </a>
                        </p>

                        <p class="text-white d-flex mt-3">
                            <i class="bi-geo-alt me-2"></i>
                            Ruse, Bulgaria
                        </p>

                        <a href="https://goo.gl/maps/d28FdCCkgSiXeHNV7" class="custom-btn btn mt-3">Get Direction</a>
                    </div>
                </div>
            </div>

            <div class="site-footer-bottom">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-6 col-md-7 col-12">
                            <p class="copyright-text mb-0">Copyright © @DateTime.UtcNow.Year; <a href="#">WeVolunteer</a></p>
                        </div>
                        
                        <div class="col-lg-6 col-md-5 col-12 d-flex justify-content-center align-items-center mx-auto">
                            <ul class="social-icon">
                                @*<li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-twitter"></a>
                                </li>*@

                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-facebook"></a>
                                </li>

                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-instagram"></a>
                                </li>

                                @*<li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-linkedin"></a>
                                </li>*@

                                @*<li class="social-icon-item">
                                    <a href="https://youtube.com/templatemo" class="social-icon-link bi-youtube"></a>
                                </li>*@
                            </ul>
                        </div>
                        
                    </div>
                </div>
            </div>
        </footer>

        <script src="~/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/bootstrap/js/jquery.sticky.js"></script>
        <script src="~/bootstrap/js/click-scroll.js"></script>
        <script src="~/bootstrap/js/counter.js"></script>
        <script src="~/bootstrap/js/custom.js"></script>
        <script src="~/lib/toastr/toastr.min.js" type="text/javascript"></script>

        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

WeVolunteer/Views/Shared/_UserMessages.cshtml
@using WeVolunteer.Core.Constants

@if(TempData[MessageConstant.ErrorMessage] != null)
{
    <script>
        $(document).ready(function() { toastr.error('@TempData[MessageConstant.ErrorMessage].ToString()'); });
    </script>
}

@if(TempData[MessageConstant.WarningMessage] != null)
{
    <script>
        $(document).ready(function() { toastr.warning('@TempData[MessageConstant.WarningMessage].ToString()'); });
    </script>
}

@if(TempData[MessageConstant.SuccessMessage] != null)
{
    <script>
        $(document).ready(function() { toastr.success('@TempData[MessageConstant.SuccessMessage].ToString()'); });
    </script>
}